name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            executable: template.exe
          - os: ubuntu-latest
            executable: template

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # - name: Cache subprojects
      #   uses: actions/cache@v4
      #   with:
      #     path: subprojects/packagecache/
      #     key: ${{ hashFiles('subprojects/*.wrap') }}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.9'
          cache: 'pip'

      - name: Install meson and ninja
        run: pip install meson ninja -r requirements.txt

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: meson setup bin --buildtype release

      - name: Compile
        run: meson compile -C bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: template-${{ github.ref }}-${{ runner.os }}
          path: bin/${{ matrix.executable }}
          if-no-files-found: error