name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # - uses: actions/cache@v4
      #   with:
      #     path: subprojects/packagecache/
      #     key: ${{ hashFiles('subprojects/*.wrap') }}

      - uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.9'
          cache: 'pip'

      - name: Install meson and ninja
        run: pip install meson ninja -r requirements.txt

      - name: Configure and compile
        run: |
          meson setup bin --buildtype release
          meson compile -C bin

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: template-linux
      #     path: |
      #       bin/template
      #     if-no-files-found: error