name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          
      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
          cache: 'pip'

      - name: Install meson and ninja
        run: pip install meson ninja -r requirements.txt

      - name: Configure and compile
        run: |
          meson bin --buildtype release
          meson compile -C bin
