name: Build

on:
  push:
    branches:
      - '*'     # dont build for tags

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: false

      # - name: Cache subprojects
      #   uses: actions/cache@v4
      #   with:
      #     path: subprojects/packagecache/
      #     key: ${{ hashFiles('subprojects/*.wrap') }}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.9'
          cache: 'pip'

      - name: Install meson and ninja
        run: pip install -r requirements.txt

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: meson setup bin --buildtype release

      - name: Compile
        run: meson install -C bin --destdir ../out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: template-${{ runner.os }}
          path: out/*
          if-no-files-found: error